project:
  type: website
  output-dir: docs

website:
  title: "My Quarto Site"
  description: "A site created with Quarto"
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Dashboard
        href: dashboard.qmd
        