# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from shiny import render, reactive, ui
from shiny.express import ui
from pathlib import Path
import openpyxl
from IPython.display import display
from functools import lru_cache

# ========================================================================




def server(input: Inputs, output: Outputs, session: Session) -> None:
    with ui.navset_pill(id="tab"):
        with ui.nav_panel("Average Effort Per Ticket"):
            "AET Content"

    # ========================================================================



    return None


_static_assets = ##STATIC_ASSETS_PLACEHOLDER##
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "demo_3.html",
    server,
    static_assets=_static_assets,
)
